CREATE TABLE inventory_items (
    id UUID PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(10) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    stock_on_hand INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(120) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by VARCHAR(120) NOT NULL,
    deleted_at TIMESTAMPTZ,
    deleted_by VARCHAR(120),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_inventory_items_type CHECK (type IN ('PART', 'SUPPLY')),
    CONSTRAINT ck_inventory_items_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_inventory_items_stock_on_hand CHECK (stock_on_hand >= 0),
    CONSTRAINT ck_inventory_items_deletion_audit
        CHECK ((deleted_at IS NULL) = (deleted_by IS NULL))
);

CREATE UNIQUE INDEX uk_inventory_items_active_name
    ON inventory_items (name)
    WHERE deleted_at IS NULL;

CREATE TABLE inventory_reservations (
    id UUID PRIMARY KEY,
    inventory_item_id UUID NOT NULL,
    service_order_id UUID NOT NULL,
    quantity INTEGER NOT NULL,
    reserved_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_inventory_reservations_item
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id),
    CONSTRAINT ck_inventory_reservations_quantity CHECK (quantity > 0)
);

CREATE UNIQUE INDEX uk_inventory_reservations_item_order
    ON inventory_reservations (inventory_item_id, service_order_id);

CREATE INDEX ix_inventory_reservations_service_order
    ON inventory_reservations (service_order_id);

CREATE TABLE inventory_audit_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id UUID NOT NULL,
    operation VARCHAR(20) NOT NULL,
    service_order_id UUID,
    quantity INTEGER,
    actor VARCHAR(120) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_inventory_audit_entries_item
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id),
    CONSTRAINT ck_inventory_audit_entries_operation
        CHECK (operation IN (
            'REGISTERED', 'UPDATED', 'REMOVED', 'REPLENISHED',
            'RESERVED', 'RELEASED', 'WITHDRAWN'
        )),
    CONSTRAINT ck_inventory_audit_entries_quantity
        CHECK (quantity IS NULL OR quantity > 0),
    CONSTRAINT ck_inventory_audit_entries_movement
        CHECK (
            (operation IN ('RESERVED', 'RELEASED', 'WITHDRAWN')
                AND service_order_id IS NOT NULL AND quantity IS NOT NULL)
            OR (operation = 'REPLENISHED'
                AND service_order_id IS NULL AND quantity IS NOT NULL)
            OR (operation IN ('REGISTERED', 'UPDATED', 'REMOVED')
                AND service_order_id IS NULL AND quantity IS NULL)
        )
);

CREATE INDEX ix_inventory_audit_entries_item_time
    ON inventory_audit_entries (inventory_item_id, occurred_at);

CREATE FUNCTION reject_inventory_audit_entry_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'inventory_audit_entries is append-only';
END;
$$;

CREATE TRIGGER trg_inventory_audit_entries_append_only
BEFORE UPDATE OR DELETE ON inventory_audit_entries
FOR EACH ROW EXECUTE FUNCTION reject_inventory_audit_entry_mutation();
