CREATE TABLE audit_trail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(60) NOT NULL,
    aggregate_id UUID NOT NULL,
    action VARCHAR(60) NOT NULL,
    actor VARCHAR(120) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_audit_trail_aggregate_time
    ON audit_trail (aggregate_type, aggregate_id, occurred_at);

CREATE FUNCTION reject_audit_trail_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit_trail is append-only';
END;
$$;

CREATE TRIGGER trg_audit_trail_append_only
BEFORE UPDATE OR DELETE ON audit_trail
FOR EACH ROW EXECUTE FUNCTION reject_audit_trail_mutation();
