CREATE TABLE audit_trail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(60) NOT NULL,
    aggregate_id UUID NOT NULL,
    action VARCHAR(60) NOT NULL,
    actor VARCHAR(120) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ck_audit_trail_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT ck_audit_trail_non_sensitive_metadata
        CHECK (NOT metadata ?| ARRAY[
            'old_value', 'new_value', 'cpf', 'cnpj', 'tax_id', 'plate', 'license_plate',
            'password', 'password_hash', 'token', 'access_token', 'refresh_token'
        ])
);

CREATE INDEX ix_audit_trail_aggregate_time
    ON audit_trail (aggregate_type, aggregate_id, occurred_at);

CREATE FUNCTION reject_audit_trail_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit_trail is append-only';
END;
$$;

CREATE TRIGGER trg_audit_trail_append_only
BEFORE UPDATE OR DELETE ON audit_trail
FOR EACH ROW EXECUTE FUNCTION reject_audit_trail_mutation();
