ALTER TABLE service_orders DROP CONSTRAINT ck_service_orders_status;
ALTER TABLE service_orders ADD CONSTRAINT ck_service_orders_status CHECK (status IN (
    'RECEIVED', 'UNDER_DIAGNOSIS', 'AWAITING_APPROVAL',
    'IN_PROGRESS', 'COMPLETED', 'DELIVERED', 'REJECTED'
));

ALTER TABLE service_order_status_history DROP CONSTRAINT ck_service_order_status_history_previous_status;
ALTER TABLE service_order_status_history ADD CONSTRAINT ck_service_order_status_history_previous_status CHECK (
    previous_status IS NULL OR previous_status IN (
        'RECEIVED', 'UNDER_DIAGNOSIS', 'AWAITING_APPROVAL',
        'IN_PROGRESS', 'COMPLETED', 'DELIVERED', 'REJECTED'
    )
);

ALTER TABLE service_order_status_history DROP CONSTRAINT ck_service_order_status_history_status;
ALTER TABLE service_order_status_history ADD CONSTRAINT ck_service_order_status_history_status CHECK (status IN (
    'RECEIVED', 'UNDER_DIAGNOSIS', 'AWAITING_APPROVAL',
    'IN_PROGRESS', 'COMPLETED', 'DELIVERED', 'REJECTED'
));

CREATE TABLE service_order_estimate_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id UUID NOT NULL,
    estimate_id UUID NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    approved_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_service_order_estimate_approvals_order
        FOREIGN KEY (service_order_id) REFERENCES service_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_service_order_estimate_approvals_estimate
        FOREIGN KEY (estimate_id) REFERENCES service_order_estimates (id) ON DELETE CASCADE,
    CONSTRAINT uk_service_order_estimate_approvals_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX ix_service_order_estimate_approvals_order
    ON service_order_estimate_approvals (service_order_id);

CREATE TABLE service_order_estimate_rejections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id UUID NOT NULL,
    estimate_id UUID NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    rejected_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_service_order_estimate_rejections_order
        FOREIGN KEY (service_order_id) REFERENCES service_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_service_order_estimate_rejections_estimate
        FOREIGN KEY (estimate_id) REFERENCES service_order_estimates (id) ON DELETE CASCADE,
    CONSTRAINT uk_service_order_estimate_rejections_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX ix_service_order_estimate_rejections_order
    ON service_order_estimate_rejections (service_order_id);

INSERT INTO service_order_estimate_approvals (service_order_id, estimate_id, idempotency_key, approved_at)
SELECT service_order_id, estimate_id, idempotency_key, occurred_at
FROM service_order_estimate_decisions
WHERE decision = 'APPROVE'
ORDER BY id;

INSERT INTO service_order_estimate_rejections (service_order_id, estimate_id, idempotency_key, rejected_at)
SELECT service_order_id, estimate_id, idempotency_key, occurred_at
FROM service_order_estimate_decisions
WHERE decision = 'REJECT'
ORDER BY id;

DROP TABLE service_order_estimate_decisions;
