spring:
  application:
    name: tech
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}

server:
  port: ${SERVER_PORT:8082}
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
    include-exception: false
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%X{traceId:-no-trace}] --- [%15.15t] %-40.40logger{39} : %m%n%wEx"
  level:
    org.hibernate.orm.jdbc.error: ERROR

resend:
  enabled: ${RESEND_ENABLED:false}
  api-key: ${RESEND_API_KEY:}
  from: ${RESEND_FROM:}
