apiVersion: v1
kind: Service
metadata:
  name: tech-api
  namespace: jacafi
spec:
  selector:
    app.kubernetes.io/name: tech-api
  ports:
    - name: http
      port: 8082
      targetPort: http
  type: ClusterIP
