package com.jacafi.tech.inventory.infrastructure.persistence;

import com.jacafi.tech.inventory.domain.DuplicateMaterialException;
import com.jacafi.tech.inventory.domain.InventoryItem;
import com.jacafi.tech.inventory.domain.InventoryItemRepository;
import com.jacafi.tech.inventory.domain.Reservation;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Repository;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

/**
 * Implements the domain port over Spring Data.
 *
 * <p>Saving an aggregate writes two tables, and the reservation rows are reconciled by hand rather
 * than by a cascade: the rows the aggregate no longer holds are deleted, the ones it holds are
 * written. Explicit because the alternative — {@code orphanRemoval} on a merged detached
 * collection — makes correctness depend on how the ORM decides to compare a collection it did not
 * load, and because the deletes must reach the database before the inserts do, which a cascade
 * gives no way to state.
 *
 * <p>Also the last line of defence for name uniqueness. The application layer checks first, so the
 * ordinary duplicate is a business rule violation with a name; what reaches here is the concurrent
 * case, where two registrations of the same name both passed that check and the partial unique
 * index settles it.
 */
@Repository
public class InventoryItemRepositoryAdapter implements InventoryItemRepository {

    /**
     * Name of the partial unique index on the material name. Postgres puts it in the message of
     * the violation it raises, which is what lets this class tell a duplicate name apart from any
     * other integrity failure instead of reporting all of them as the same thing.
     */
    private static final String ACTIVE_NAME_INDEX = "ux_inventory_items_name_active";

    private final InventoryItemJpaRepository itemRepository;
    private final InventoryReservationJpaRepository reservationRepository;
    private final InventoryPersistenceMapper mapper;

    public InventoryItemRepositoryAdapter(InventoryItemJpaRepository itemRepository,
                                          InventoryReservationJpaRepository reservationRepository,
                                          InventoryPersistenceMapper mapper) {
        this.itemRepository = itemRepository;
        this.reservationRepository = reservationRepository;
        this.mapper = mapper;
    }

    @Override
    public void save(InventoryItem item) {
        try {
            // The identifier is assigned by the application, never generated by the database, so
            // Spring Data treats the entity as detached and merges it. That costs a select before
            // an insert, which is the price of having no setters to mutate a managed instance.
            itemRepository.save(mapper.toEntity(item));
            syncReservations(item);
            itemRepository.flush();
        } catch (DataIntegrityViolationException e) {
            if (namesActiveNameIndex(e)) {
                throw new DuplicateMaterialException(
                        "A material with this name is already registered.");
            }
            throw e;
        }
    }

    @Override
    public Optional<InventoryItem> findActiveById(UUID id) {
        return itemRepository.findByIdAndRemovedAtIsNull(id).map(this::toDomain);
    }

    @Override
    public Optional<InventoryItem> findActiveByIdForUpdate(UUID id) {
        return itemRepository.findForUpdateByIdAndRemovedAtIsNull(id).map(this::toDomain);
    }

    @Override
    public boolean existsActiveWithName(String name) {
        return itemRepository.existsByNameIgnoreCaseAndRemovedAtIsNull(name);
    }

    @Override
    public boolean existsActiveWithNameExcluding(String name, UUID excludedId) {
        return itemRepository.existsByNameIgnoreCaseAndIdNotAndRemovedAtIsNull(name, excludedId);
    }

    private InventoryItem toDomain(InventoryItemJpaEntity entity) {
        return mapper.toDomain(entity, reservationRepository.findByInventoryItemId(entity.getId()));
    }

    /**
     * Brings the reservation rows in line with what the aggregate now holds.
     *
     * <p>Deletes are flushed before the writes. A reservation keeps its identity when it grows, so
     * the two sets never overlap today; flushing anyway means a future command that settles a
     * reservation and opens another for the same order in one transaction does not trip the unique
     * index on (item, order) because Hibernate happened to order its inserts first.
     */
    private void syncReservations(InventoryItem item) {
        Map<UUID, InventoryReservationJpaEntity> stored = new LinkedHashMap<>();
        for (InventoryReservationJpaEntity row : reservationRepository.findByInventoryItemId(item.getId())) {
            stored.put(row.getId(), row);
        }

        List<Reservation> open = item.getReservations();
        List<InventoryReservationJpaEntity> obsolete = stored.entrySet().stream()
                .filter(entry -> open.stream().noneMatch(reservation -> reservation.id().equals(entry.getKey())))
                .map(Map.Entry::getValue)
                .toList();

        if (!obsolete.isEmpty()) {
            reservationRepository.deleteAll(obsolete);
            reservationRepository.flush();
        }

        for (Reservation reservation : open) {
            InventoryReservationJpaEntity existing = stored.get(reservation.id());
            if (existing == null || existing.getQuantity() != reservation.quantity().value()) {
                reservationRepository.save(mapper.toEntity(item.getId(), reservation));
            }
        }
    }

    private static boolean namesActiveNameIndex(DataIntegrityViolationException e) {
        String message = e.getMostSpecificCause().getMessage();
        return message != null && message.contains(ACTIVE_NAME_INDEX);
    }
}
