package com.jacafi.tech.vehicle.infrastructure.persistence;

import com.jacafi.tech.vehicle.domain.DuplicateLicensePlateException;
import com.jacafi.tech.vehicle.domain.LicensePlate;
import com.jacafi.tech.vehicle.domain.Vehicle;
import com.jacafi.tech.vehicle.domain.VehicleRepository;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * Implements the domain port over Spring Data.
 *
 * <p>Also the last line of defence for plate uniqueness. The application layer checks first, so
 * the ordinary duplicate is a business rule violation with a name; what reaches here is the
 * concurrent case, where two registrations of the same plate both passed that check and the
 * partial unique index in the database settles it. Translating the constraint violation back into
 * {@link DuplicateLicensePlateException} means the caller sees one failure, not two.
 */
@Repository
public class VehicleRepositoryAdapter implements VehicleRepository {

    private final VehicleJpaRepository jpaRepository;
    private final VehiclePersistenceMapper mapper;

    public VehicleRepositoryAdapter(VehicleJpaRepository jpaRepository, VehiclePersistenceMapper mapper) {
        this.jpaRepository = jpaRepository;
        this.mapper = mapper;
    }

    @Override
    public void save(Vehicle vehicle) {
        try {
            // The identifier is assigned by the application, never generated by the database, so
            // Spring Data treats the entity as detached and merges it. That costs a select before
            // an insert, which is the price of having no setters to mutate a managed instance.
            jpaRepository.save(mapper.toEntity(vehicle));
            jpaRepository.flush();
        } catch (DataIntegrityViolationException e) {
            throw new DuplicateLicensePlateException(
                    "A vehicle with this license plate is already registered.");
        }
    }

    @Override
    public Optional<Vehicle> findActiveById(UUID id) {
        return jpaRepository.findByIdAndRemovedAtIsNull(id).map(mapper::toDomain);
    }

    @Override
    public Optional<Vehicle> findActiveByLicensePlate(LicensePlate licensePlate) {
        return jpaRepository.findByLicensePlateAndRemovedAtIsNull(licensePlate.value()).map(mapper::toDomain);
    }

    @Override
    public boolean existsActiveWithLicensePlate(LicensePlate licensePlate) {
        return jpaRepository.existsByLicensePlateAndRemovedAtIsNull(licensePlate.value());
    }
}
